import { type NextPage } from "next";
import Head from "next/head";

import { Timeline } from "../components/Timeline";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Twit3r</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>Twit3r</h1>

        <Timeline />
      </div>
    </>
  );
};

export default Home;
